"""rename repo_path to repo_url add branch and repo_local_path

Revision ID: 249d9333c9b1
Revises: c9ba215186c3
Create Date: 2026-04-23 16:18:49.356361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249d9333c9b1'
down_revision: Union[str, Sequence[str], None] = 'c9ba215186c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('workflows', sa.Column('repo_url', sa.String(length=500), nullable=True))
    op.add_column('workflows', sa.Column('branch', sa.String(length=255), nullable=True))
    op.add_column('workflows', sa.Column('repo_local_path', sa.String(length=500), nullable=True))

    op.execute("UPDATE workflows SET repo_url = repo_path WHERE repo_url IS NULL")

    op.alter_column('workflows', 'repo_url', nullable=False)
    op.drop_column('workflows', 'repo_path')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('repo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('workflows', 'repo_local_path')
    op.drop_column('workflows', 'branch')
    op.drop_column('workflows', 'repo_url')
    # ### end Alembic commands ###
