"""make service_id nullable on workflows

Revision ID: 2bbad823c230
Revises: e1a9a82f0512
Create Date: 2026-04-26 22:55:14.393470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbad823c230'
down_revision: Union[str, Sequence[str], None] = 'e1a9a82f0512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
