"""add pr_url to workflows

Revision ID: e1a9a82f0512
Revises: e029ef956c20
Create Date: 2026-04-23 22:31:39.269311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a9a82f0512'
down_revision: Union[str, Sequence[str], None] = 'e029ef956c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('pr_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'pr_url')
    # ### end Alembic commands ###
